function dnsapp() {
    CD=`pwd`
    pushd $DNSAPP_DIR;
    if [ $1 ]
    then
        export DJANGO_SETTINGS_MODULE=$DNSAPP_SETTINGS
        ./manage.py $@;
        if [ "$CD" != "`pwd`" ]
        then
            popd;
        fi
    fi
    unset CD;
}
